#!/bin/bash
set -e

# ─── Generate config.lua from environment variables ───────────────────────────
cat > /app/server/config.lua << EOF
-- Auto-generated by entrypoint.sh — do not edit manually
-- Edit the .env file in the repo root to change settings

-- ── World ─────────────────────────────────────────────────────────────────────
worldType              = "${WORLD_TYPE:-pvp}"
serverName             = "${SERVER_NAME:-Tibia 7.4}"
motd                   = "${MOTD:-Welcome to Tibia 7.4!}"
location               = "${LOCATION:-World}"
url                    = "${SERVER_URL:-}"
ownerName              = "${OWNER_NAME:-Admin}"
ownerEmail             = "${OWNER_EMAIL:-admin@localhost}"

-- ── Connection ────────────────────────────────────────────────────────────────
ip                     = "0.0.0.0"
bindOnlyGlobalAddress  = false
loginProtocolPort      = 7171
gameProtocolPort       = 7172
statusProtocolPort     = 7171
maxPlayers             = 0
maxPacketsPerSecond    = 25
statusTimeout          = 5000
replaceKickOnLogin     = true

-- ── Database ──────────────────────────────────────────────────────────────────
mysqlHost              = "${TFS_MYSQL_HOST:-127.0.0.1}"
mysqlUser              = "${TFS_MYSQL_USER:-tibia}"
mysqlPass              = "${TFS_MYSQL_PASSWORD:-tibia_password}"
mysqlDatabase          = "${TFS_MYSQL_DATABASE:-tibia}"
mysqlPort              = ${TFS_MYSQL_PORT:-3306}
mysqlSock              = ""
passwordType           = "sha1"

-- ── Rates ─────────────────────────────────────────────────────────────────────
rateExp                = ${RATE_EXP:-5}
rateSkill              = ${RATE_SKILL:-3}
rateLoot               = ${RATE_LOOT:-2}
rateMagic              = ${RATE_MAGIC:-3}
rateSpawn              = 1

-- ── Combat ────────────────────────────────────────────────────────────────────
protectionLevel        = 1
killsToRedSkull        = 3
killsToBlackSkull      = 6
pzLocked               = 60000
removeChargesFromRunes = true
timeToDecreaseFrags    = 24 * 60 * 60 * 1000
whiteSkullTime         = 15 * 60 * 1000
stairJumpExhaustion    = 2000
experienceByKillingPlayers = false
expFromPlayersLevelRange   = 75

-- ── Deaths ────────────────────────────────────────────────────────────────────
deathLosePercent       = -1

-- ── Map ───────────────────────────────────────────────────────────────────────
mapName                = "world"
mapAuthor              = "ond"

-- ── Houses ────────────────────────────────────────────────────────────────────
housePriceEachSQM      = 1000
houseRentPeriod        = "never"

-- ── Misc ──────────────────────────────────────────────────────────────────────
allowChangeOutfit      = true
freePremium            = false
kickIdlePlayerAfterMinutes = 15
maxMessageBuffer       = 4
emoteSpells            = false
classicEquipmentSlots  = false
summonsDropCorpse      = true
displayLootMessage     = false
warnUnsafeScripts      = true
convertUnsafeScripts   = true
timeBetweenActions     = 200
timeBetweenExActions   = 1000
deSpawnRange           = 2
deSpawnRadius          = 50
startupDatabaseOptimization = false
onePlayerOnlinePerAccount   = true
allowClones            = false
EOF

echo "[entrypoint] config.lua generated."
echo "[entrypoint] Starting The Forgotten Server..."

cd /app/server
exec /app/theforgottenserver
